-- UAT fixture: schema from read-only Neon catalog 2026-10-08, synthetic rows, then the migration twice. No production rows or credentials.
CREATE TABLE public.lands (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "public_ref" int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title_th" text NOT NULL,
  "slug" text NOT NULL,
  "province_id" uuid NOT NULL,
  "district" text,
  "land_type" text NOT NULL,
  "size_rai" numeric(14,5),
  "zoning" text,
  "frontage_m" numeric(10,2),
  "price_per_rai" numeric(16,2),
  "total_price" numeric(18,2),
  "referral_reward_max" numeric(16,2),
  "is_eec" bool DEFAULT false NOT NULL,
  "nearby_landmarks" text[],
  "description" text,
  "lat" numeric(10,7),
  "lng" numeric(10,7),
  "location_precision" text DEFAULT 'approx'::text NOT NULL,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "is_featured" bool DEFAULT false NOT NULL,
  "seo_title" text,
  "seo_description" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "deleted_at" timestamptz,
  "owner_lead_id" uuid,
  "property_type" text DEFAULT 'land'::text NOT NULL,
  "transaction_type" text DEFAULT 'sale'::text NOT NULL,
  "subdistrict" text,
  "address" text,
  "area_rai" int4,
  "area_ngan" int4,
  "area_sqwa" numeric(10,2),
  "depth_min_m" numeric(12,2),
  "depth_max_m" numeric(12,2),
  "road_name" text,
  "road_width_m" numeric(12,2),
  "rent_price_monthly" numeric(16,2),
  "verification_status" text DEFAULT 'pending'::text NOT NULL,
  "published_at" timestamptz,
  "usable_area_sqm" numeric(14,2)
);
CREATE TABLE public.property_submissions (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "draft_token" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" text,
  "owner_lead_id" uuid,
  "linked_land_id" uuid,
  "property_type" text,
  "transaction_type" text DEFAULT 'sale'::text,
  "title" text,
  "province_id" uuid,
  "district" text,
  "subdistrict" text,
  "address" text,
  "lat" numeric(10,7),
  "lng" numeric(10,7),
  "location_precision" text DEFAULT 'approx'::text,
  "area_rai" int4,
  "area_ngan" int4,
  "area_sqwa" numeric(10,2),
  "total_rai" numeric(14,5),
  "frontage_m" numeric(12,2),
  "depth_min_m" numeric(12,2),
  "depth_max_m" numeric(12,2),
  "road_name" text,
  "road_width_m" numeric(12,2),
  "zoning" text,
  "sale_price" numeric(16,2),
  "price_per_rai" numeric(16,2),
  "rent_price_monthly" numeric(16,2),
  "description" text,
  "contact_name" text,
  "contact_phone" text,
  "contact_line" text,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "verification_status" text DEFAULT 'pending'::text NOT NULL,
  "review_note" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "submitted_at" timestamptz,
  "reviewed_at" timestamptz,
  "published_at" timestamptz,
  "usable_area_sqm" numeric(14,2)
);
CREATE TABLE public.property_submission_media (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "submission_id" uuid NOT NULL,
  "media_kind" text NOT NULL,
  "file_name" text NOT NULL,
  "storage_key" text NOT NULL,
  "public_url" text,
  "mime_type" text NOT NULL,
  "size_bytes" int8 NOT NULL,
  "doc_type" text,
  "sort_order" int4 DEFAULT 0 NOT NULL,
  "is_cover" bool DEFAULT false NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE public.provinces (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name_th" text NOT NULL,
  "name_en" text NOT NULL,
  "slug" text NOT NULL,
  "region" text,
  "lat" numeric(10,6),
  "lng" numeric(10,6),
  "created_at" timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE public.land_images (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "land_id" uuid NOT NULL,
  "storage_key" text NOT NULL,
  "url_or_cdn_path" text NOT NULL,
  "mime_type" text,
  "size_bytes" int8,
  "width" int4,
  "height" int4,
  "alt_th" text,
  "sort_order" int4 DEFAULT 0 NOT NULL,
  "is_cover" bool DEFAULT false NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE public.land_documents (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "land_id" uuid,
  "file_name" text NOT NULL,
  "storage_key" text NOT NULL,
  "mime_type" text NOT NULL,
  "size_bytes" int8 NOT NULL,
  "doc_type" text DEFAULT 'other'::text NOT NULL,
  "is_sensitive" bool DEFAULT true NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE public.leads (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "lead_type" text NOT NULL,
  "name" text NOT NULL,
  "phone" text NOT NULL,
  "line_id" text,
  "source" text,
  "referral_code" text,
  "status" text DEFAULT 'new'::text NOT NULL,
  "assigned_to" text,
  "next_action_at" timestamptz,
  "last_reminded_at" timestamptz,
  "reminder_claim_token" uuid,
  "reminder_claimed_at" timestamptz,
  "reminder_claimed_for" timestamptz,
  "details" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "consent_pdpa" bool DEFAULT false NOT NULL,
  "consent_at" timestamptz,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);
CREATE TABLE public.site_stats (
  "id" int4 DEFAULT 1 NOT NULL,
  "total_partners" int4 DEFAULT 0 NOT NULL,
  "total_listings" int4 DEFAULT 0 NOT NULL,
  "total_deals" int4 DEFAULT 0 NOT NULL,
  "total_payout_mb" numeric(10,1) DEFAULT 0 NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);
ALTER TABLE public.land_documents ADD CONSTRAINT "land_documents_doc_type_check" CHECK ((doc_type = ANY (ARRAY['title_deed'::text, 'map'::text, 'brochure'::text, 'other'::text])));
ALTER TABLE public.site_stats ADD CONSTRAINT "site_stats_id_check" CHECK ((id = 1));
ALTER TABLE public.property_submission_media ADD CONSTRAINT "property_submission_media_pkey" PRIMARY KEY (id);
ALTER TABLE public.property_submission_media ADD CONSTRAINT "property_submission_media_storage_key_key" UNIQUE (storage_key);
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_area_ngan_check" CHECK (((area_ngan IS NULL) OR ((area_ngan >= 0) AND (area_ngan <= 3))));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_area_sqwa_check" CHECK (((area_sqwa IS NULL) OR ((area_sqwa >= (0)::numeric) AND (area_sqwa < (100)::numeric))));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_draft_token_key" UNIQUE (draft_token);
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_location_precision_check" CHECK ((location_precision = ANY (ARRAY['exact'::text, 'approx'::text])));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_pkey" PRIMARY KEY (id);
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_property_type_check" CHECK (((property_type IS NULL) OR (property_type = ANY (ARRAY['land'::text, 'house'::text, 'house_with_land'::text, 'townhouse'::text, 'condo'::text, 'housing_project'::text, 'commercial_building'::text, 'office'::text, 'factory'::text, 'warehouse'::text, 'apartment'::text, 'hotel_resort'::text, 'retail'::text, 'business_property'::text, 'other'::text]))));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'approved'::text, 'published'::text, 'rejected'::text, 'sold'::text, 'expired'::text])));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_transaction_type_check" CHECK (((transaction_type IS NULL) OR (transaction_type = 'sale'::text)));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_usable_area_check" CHECK (((usable_area_sqm IS NULL) OR (usable_area_sqm >= (0)::numeric)));
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_verification_check" CHECK ((verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])));
ALTER TABLE public.provinces ADD CONSTRAINT "provinces_pkey" PRIMARY KEY (id);
ALTER TABLE public.provinces ADD CONSTRAINT "provinces_slug_key" UNIQUE (slug);
ALTER TABLE public.leads ADD CONSTRAINT "leads_status_check" CHECK ((status = ANY (ARRAY['new'::text, 'contacting'::text, 'qualified'::text, 'won'::text, 'lost'::text])));
ALTER TABLE public.leads ADD CONSTRAINT "leads_pkey" PRIMARY KEY (id);
ALTER TABLE public.property_submission_media ADD CONSTRAINT "property_submission_media_kind_check" CHECK ((media_kind = ANY (ARRAY['image'::text, 'document'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_zoning_check" CHECK (((zoning IS NULL) OR (zoning = ANY (ARRAY['purple'::text, 'purple_light'::text, 'brown'::text, 'orange'::text, 'yellow'::text, 'green'::text, 'other'::text]))));
ALTER TABLE public.land_documents ADD CONSTRAINT "land_documents_pkey" PRIMARY KEY (id);
ALTER TABLE public.land_images ADD CONSTRAINT "land_images_pkey" PRIMARY KEY (id);
ALTER TABLE public.lands ADD CONSTRAINT "lands_land_type_check" CHECK ((land_type = ANY (ARRAY['industrial'::text, 'eec'::text, 'logistics'::text, 'data_center'::text, 'investment'::text, 'land'::text, 'house'::text, 'house_with_land'::text, 'townhouse'::text, 'condo'::text, 'housing_project'::text, 'commercial_building'::text, 'office'::text, 'factory'::text, 'warehouse'::text, 'apartment'::text, 'hotel_resort'::text, 'retail'::text, 'business_property'::text, 'other'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_location_precision_check" CHECK ((location_precision = ANY (ARRAY['exact'::text, 'approx'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_pkey" PRIMARY KEY (id);
ALTER TABLE public.leads ADD CONSTRAINT "leads_lead_type_check" CHECK ((lead_type = ANY (ARRAY['buyer'::text, 'partner'::text, 'owner'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_property_type_check" CHECK ((property_type = ANY (ARRAY['land'::text, 'house'::text, 'house_with_land'::text, 'townhouse'::text, 'condo'::text, 'housing_project'::text, 'commercial_building'::text, 'office'::text, 'factory'::text, 'warehouse'::text, 'apartment'::text, 'hotel_resort'::text, 'retail'::text, 'business_property'::text, 'other'::text])));
ALTER TABLE public.site_stats ADD CONSTRAINT "site_stats_pkey" PRIMARY KEY (id);
ALTER TABLE public.lands ADD CONSTRAINT "lands_public_ref_key" UNIQUE (public_ref);
ALTER TABLE public.lands ADD CONSTRAINT "lands_status_check" CHECK ((status = ANY (ARRAY['draft'::text, 'active'::text, 'reserved'::text, 'sold'::text, 'archived'::text, 'expired'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_transaction_type_check" CHECK ((transaction_type = 'sale'::text));
ALTER TABLE public.lands ADD CONSTRAINT "lands_usable_area_check" CHECK (((usable_area_sqm IS NULL) OR (usable_area_sqm >= (0)::numeric)));
ALTER TABLE public.lands ADD CONSTRAINT "lands_verification_status_check" CHECK ((verification_status = ANY (ARRAY['pending'::text, 'verified'::text, 'rejected'::text])));
ALTER TABLE public.lands ADD CONSTRAINT "lands_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id);
ALTER TABLE public.lands ADD CONSTRAINT "lands_owner_lead_id_fkey" FOREIGN KEY (owner_lead_id) REFERENCES leads(id) ON DELETE SET NULL;
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_province_id_fkey" FOREIGN KEY (province_id) REFERENCES provinces(id);
ALTER TABLE public.property_submission_media ADD CONSTRAINT "property_submission_media_submission_id_fkey" FOREIGN KEY (submission_id) REFERENCES property_submissions(id) ON DELETE CASCADE;
ALTER TABLE public.land_images ADD CONSTRAINT "land_images_land_id_fkey" FOREIGN KEY (land_id) REFERENCES lands(id) ON DELETE CASCADE;
ALTER TABLE public.land_documents ADD CONSTRAINT "land_documents_land_id_fkey" FOREIGN KEY (land_id) REFERENCES lands(id) ON DELETE SET NULL;
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_linked_land_id_fkey" FOREIGN KEY (linked_land_id) REFERENCES lands(id) ON DELETE SET NULL;
ALTER TABLE public.property_submissions ADD CONSTRAINT "property_submissions_owner_lead_id_fkey" FOREIGN KEY (owner_lead_id) REFERENCES leads(id) ON DELETE SET NULL;-- Synthetic pre-migration rows mirroring the production shapes seen read-only (not production data).
INSERT INTO public.provinces (name_th, name_en, slug) VALUES ('ฟิกซ์เจอร์', 'Fixture', 'zoning-fixture');
INSERT INTO public.lands (title_th, slug, province_id, land_type, zoning, status, verification_status)
SELECT title, slug, (SELECT id FROM public.provinces WHERE slug = 'zoning-fixture'), 'industrial', zoning, 'active', 'verified'
FROM (VALUES ('กบินทร์บุรี 101 ไร่', '101-rai-kabin-buri', NULL), ('ม่วงเดิม', 'legacy-purple-verified', 'purple')) AS v(title, slug, zoning);
\ir ../neon/migrations/202610080001_zoning_info.sql
\ir ../neon/migrations/202610080001_zoning_info.sql
